//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseEntityFramework.Entidades
{
    using System;
    
    public partial class AlumnosPorCurso
    {
        public int AlumnoCursoId { get; set; }
        public string Alumno { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string Curso { get; set; }
        public int NroCreditos { get; set; }
    }
}
