//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseEntityFramework.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCurso
    {
        public int AlumnoCursoId { get; set; }
        public int AlumnoId { get; set; }
        public int CursoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
